from django.urls import path
from .views import *

urlpatterns = [
	# path("message/create", create_message),
	# path("message/get", get_message),
	# path("message/update", update_message),
	# path("message/delete", delete_message),
	path("agecategory/create", create_agecategory),
	path("agecategory/get", get_agecategory),
	path("agecategory/update", update_agecategory),
	path("agecategory/delete", delete_agecategory),
	path("transporttype/create", create_transporttype),
	path("transporttype/get", get_transporttype),
	path("transporttype/update", update_transporttype),
	path("transporttype/delete", delete_transporttype),
	path("availablelanguage/create", create_availablelanguage),
	path("availablelanguage/get", get_availablelanguage),
	path("availablelanguage/update", update_availablelanguage),
	path("availablelanguage/delete", delete_availablelanguage),
	path("hotelcategory/create", create_hotelcategory),
	path("hotelcategory/get", get_hotelcategory),
	path("hotelcategory/update", update_hotelcategory),
	path("hotelcategory/delete", delete_hotelcategory),
	path("roomtype/create", create_roomtype),
	path("roomtype/get", get_roomtype),
	path("roomtype/update", update_roomtype),
	path("roomtype/delete", delete_roomtype),
	path("mealplan/create", create_mealplan),
	path("mealplan/get", get_mealplan),
	path("mealplan/update", update_mealplan),
	path("mealplan/delete", delete_mealplan),
	path("accommodation/create", create_accommodation),
	path("accommodation/get", get_accommodation),
	path("accommodation/update", update_accommodation),
	path("accommodation/delete", delete_accommodation),
	path("currency/create", create_currency),
	path("currency/get", get_currency),
	path("currency/update", update_currency),
	path("currency/delete", delete_currency),
    path("tourtype/get", get_tour_types),

	path("review/post", post_review),
	path("review/get", get_review),
]